# Generated by Django 2.2.2 on 2019-07-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaurd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='guest_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intime', models.CharField(max_length=100)),
                ('extime', models.CharField(max_length=100)),
                ('gs_name', models.CharField(max_length=100)),
                ('gs_from', models.CharField(max_length=100)),
                ('gs_purpose', models.CharField(max_length=100)),
            ],
        ),
    ]
