# Generated by Django 2.2.2 on 2019-07-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaurd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='guest_enteries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intime', models.CharField(max_length=100)),
                ('extime', models.CharField(max_length=100)),
                ('guest_name', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('comefrom', models.CharField(max_length=100)),
            ],
        ),
    ]
